type: depth_anything
name: depth_anything_vit_s-r20240124
display_name: Depth Anything (ViT-Small)
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.3.1/depth_anything_vits14.onnx