type: segment_anything
name: lvm_sam_ssk_buid_vit_b-r20230810
display_name: LVM-Med BUID SAM (ViT-Base)
encoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_model_best_large_ssl_buidnewprocess.encoder.onnx
decoder_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v0.2.0/sam_model_best_large_ssl_buidnewprocess.decoder.onnx
input_size: 1024
max_width: 1024
max_height: 682
