type: rtmdet_pose
name: rtmdet_m_coco_person_rtmo_m-r20240112
display_name: RTMDet-M-RTMO-M OpenMMLab
det_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.3.0/rtmdet_m_640-8xb32_coco-person.onnx
pose_model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.3.0/rtmo_m.onnx
pose: rtmo
draw_det_box: True
kpt_threshold: 0.3
score_threshold: 0.45
keypoints:
  - nose
  - left_eye
  - right_eye
  - left_ear
  - right_ear
  - left_shoulder
  - right_shoulder
  - left_elbow
  - right_elbow
  - left_wrist
  - right_wrist
  - left_hip
  - right_hip
  - left_knee
  - right_knee
  - left_ankle
  - right_ankle