type: yolov8_pose
name: yolov8n-pose-r20231103
display_name: YOLOv8n-Pose Ultralytics
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v1.0.0/yolov8n-pose.onnx
confidence_threshold: 0.5
nms_threshold: 0.6
show_boxes: True
classes:
  - person
keypoints:
  - nose
  - left_eye
  - right_eye
  - left_ear
  - right_ear
  - left_shoulder
  - right_shoulder
  - left_elbow
  - right_elbow
  - left_wrist
  - right_wrist
  - left_hip
  - right_hip
  - left_knee
  - right_knee
  - left_ankle
  - right_ankle
